
filter:
    excluded_paths: [vendor/*, tests/*]

checks:
    php:
        code_rating: true
        duplication: true

tools:
    php_cs_fixer: false
    external_code_coverage:
        timeout: 1800
