sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  matrix:
    - DRIVER="phpdbg" DEPENDENCIES="high"

  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

matrix:
  include:
    - php: 7
    - php: 7.1
  allow_failures:
    - php: 7

install:
  - travis_retry composer install --no-interaction

script:
 - if [[ "$DRIVER" = 'phpdbg' ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
