sudo: false

language: php

os:
  - linux

services:
  - redis-server
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

env:
  matrix:
    - DRIVER="phpdbg" DEPENDENCIES="high"

  global:
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

matrix:
  include:
    - php: 7.2

before_install:
  - phpenv config-rm xdebug.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - travis_retry composer install --no-interaction

before_script:
  - mysql -e 'create database nymfonya DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'
  - mysql -u root -e "create user 'travis_pass'@'localhost' identified by 'some password';"
  - mysql -u root -e "grant all on nymfonya.* to 'travis_pass'@'localhost';"
  - mysql -u travis_pass -p 'some password' -e 'show databases'

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.clover

after_success:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
